// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAxLcad7wpXEIDHKE3Xjvz9Hk_93pd65Q',
    appId: '1:671845243604:web:1373220e3775cc9032b941',
    messagingSenderId: '671845243604',
    projectId: 'vodafone-tech-app',
    authDomain: 'vodafone-tech-app.firebaseapp.com',
    storageBucket: 'vodafone-tech-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1erBBVnton6xsoy6CTiPwlxZGsIxYNnY',
    appId: '1:671845243604:android:9d9db8b93a8552cf32b941',
    messagingSenderId: '671845243604',
    projectId: 'vodafone-tech-app',
    storageBucket: 'vodafone-tech-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0-sjrFsH-_rbsFEys2D9NdEh4CDz8qU',
    appId: '1:671845243604:ios:b177b883e4da5d2b32b941',
    messagingSenderId: '671845243604',
    projectId: 'vodafone-tech-app',
    storageBucket: 'vodafone-tech-app.firebasestorage.app',
    iosBundleId: 'com.example.vodafoneTechNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0-sjrFsH-_rbsFEys2D9NdEh4CDz8qU',
    appId: '1:671845243604:ios:b177b883e4da5d2b32b941',
    messagingSenderId: '671845243604',
    projectId: 'vodafone-tech-app',
    storageBucket: 'vodafone-tech-app.firebasestorage.app',
    iosBundleId: 'com.example.vodafoneTechNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAxLcad7wpXEIDHKE3Xjvz9Hk_93pd65Q',
    appId: '1:671845243604:web:6d058daab8be5f3e32b941',
    messagingSenderId: '671845243604',
    projectId: 'vodafone-tech-app',
    authDomain: 'vodafone-tech-app.firebaseapp.com',
    storageBucket: 'vodafone-tech-app.firebasestorage.app',
  );
}
